### ISSUE TITLE
C compiler CXX compiler identification is unknown

### ISSUE THREAD

**Issue by FredericVincent0** [mikage-emu/mikage-dev#16]
![Capture d’écran 2024-12-28 164959](https://github.com/user-attachments/assets/2133e61b-fbaa-48e2-91f4-107f2111caaa)

**Comment by Ch-Rad** [comment]
I think you either don't have the compiler installed at all or the path variables for the compiler are not set up.
If you don't have the compiler installed you can use [this](https://stackoverflow.com/a/30071634) answer on stackoverflow as a guide to install it using msys2. Also remember to add it to path.

**Comment by neobrain** [comment]
Building on Windows is not actively tested, but patches to improve the building experience are welcome.
