### ISSUE TITLE
Configuring incomplete, errors occurred

### ISSUE THREAD

**Issue by FredericVincent0** [mikage-emu/mikage-dev#19]
![Capture d’écran 2024-12-29 064946](https://github.com/user-attachments/assets/30ef22a2-378c-4c85-839e-5f046d300970)

**Comment by neobrain** [comment]
Sorry for being unclear in your previous issue report. This issue tracker is not intended for support. Some amount of autonomic problem solving is expected at this stage of the project.

**Comment by FredericVincent0** [comment]
Ok i understand

Le dim. 29 déc. 2024, 07 h 40, Tony Wasserka ***@***.***> a
écrit :
