### ISSUE TITLE
A Small Questionnaire: Does Mikage Currently Support OpenGL?

### ISSUE THREAD

**Issue by 2390680183** [mikage-emu/mikage-dev#20]
Hello, I'm really interested in the Mikage emulator. However, my mobile phone doesn't support Vulkan. I was wondering if there are any plans to make it support OpenGL or other alternatives in the future so that I can also use this emulator on my device? Thanks a lot for your attention and hard work.

**Comment by neobrain** [comment]
Vulkan is a hard requirement of the emulator. Other APIs may be supported in the future, but OpenGL support would have to be an external contribution with a solidly illustrated use case.
